import { contentOfGC } from './gc';

describe('contentGC()', () => {
  const fastaTest1 = `>Rosalind_6404
  CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCC
  TCCCACTAATAATTCTGAGG
  >Rosalind_5959
  CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCT
  ATATCCATTTGTCAGCAGACACGC
  >Rosalind_0808
  CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGAC
  TGGGAACCTGCGGGCAGTAGGTGGAAT`;

  const fastaTest2 = `>Rosalind_5150
  ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCTCTGCC
  CCTGGAGGGTGGCCCCACCGGCCG
  >Rosalind_0707
  AGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGC
  CTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGG
  >Rosalind_0423
  AAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCC
  CTGCAGGAACTTCTTCTG
  >Rosalind_0616
  GAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAA`;

  test('FASTA String 1', () => {
    expect(contentOfGC(fastaTest1)).toEqual('Rosalind_0808\n60.91954022988506');
  });

  test('FASTA String 2', () => {
    expect(contentOfGC(fastaTest2)).toEqual('Rosalind_5150\n73.40425531914893');
  });
});