import { contentOfGC } from './gc';

describe('contentOfGC()', () => {
  test('Test FASTA 1', () => {
    const fastaTest1 = `>Rosalind_6404
    CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAA
    TAATTCTGAGG
    >Rosalind_5959
    CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATT
    TGTCAGCAGACACGC
    >Rosalind_0808
    CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCT
    GCGGGCAGTAGGTGGAAT`;

    expect(contentOfGC(fastaTest1)).toEqual('Rosalind_0808\n60.91954022988506');
  });
});