import { contentOfGC } from './gc';

<<<<<<< HEAD
describe('computeGC()', () => {
<<<<<<< HEAD
  test
=======
  test('ATGC', () => {
    expect(computeGC('ATCG')).toEqual(.5);
=======
describe('contentOfGC()', () => {
  const fastaTest1 = `>Rosalind_6404
  CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAA
  TAATTCTGAGG
  >Rosalind_5959
  CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATT
  TGTCAGCAGACACGC
  >Rosalind_0808
  CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCT
  GCGGGCAGTAGGTGGAAT`;

  const fastaTest2 = `>Rosalind_5150
  ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCTCTGC
  CCCTGGAGGGTGGCCCCACCGGCCG
  >Rosalind_0707
  AGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGCCTCCTGACTTTCCTCGCTTGGTG
  GTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGG
  >Rosalind_0423
  AAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGC
  CCTGCAGGAACTTCTTCTG
  >Rosalind_0616
  GAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAA`;

  test(`${fastaTest1}`, () => {
    expect(contentOfGC(fastaTest1)).toEqual('Rosalind_0808\n60.91954022988506');
  });

  test(`${fastaTest2}`, () => {
    expect(contentOfGC(fastaTest2)).toEqual('Rosalind_5150\n73.40425531914893');
>>>>>>> 05-test-suite
  });
>>>>>>> 05-test-suite
});